#!/usr/bin/env bash
set -x
export DB_REF_DEFAULT_DBNAME=${DB_REF_DEFAULT_DBNAME}
export DB_REF_HOSTNAME=${DB_REF_HOSTNAME}
export DB_REF_PORT=${DB_REF_PORT}
export DB_REF_OPTIONS=${DB_REF_OPTIONS}

export DB_REF_DEFAULT_USERNAME=${DB_REF_DEFAULT_USERNAME}
export DB_REF_DEFAULT_PASSWORD=${DB_REF_DEFAULT_PASSWORD}
export ROOT_URL="postgresql://${DB_REF_DEFAULT_USERNAME}:${DB_REF_DEFAULT_PASSWORD}@${DB_REF_HOSTNAME}:${DB_REF_PORT}/${DB_REF_DEFAULT_DBNAME}${DB_REF_OPTIONS}"

export DB_REF_REFERENCE_DBNAME=${DB_REF_REFERENCE_DBNAME}

export GOVERNANCE_OWNERNAME=${DB_REF_GOVERNANCE_OWNER_USERNAME}
export GOVERNANCE_OWNERPASSWORD=${DB_REF_GOVERNANCE_OWNER_PASSWORD}
export REFERENCE_OWNERNAME=${DB_REF_REFERENCE_OWNER_USERNAME}

export REFERENCE_AUTHENTICATOR_USERNAME=${DB_REF_REFERENCE_AUTHENTICATOR_USERNAME}
export REFERENCE_ANONUSERNAME=${DB_REF_REFERENCE_ANON_USERNAME}
export REFERENCE_SERVICEUSERNAME=${DB_REF_REFERENCE_SERVICE_USERNAME}
export REFERENCE_READONLYUSERNAME=${DB_REF_REFERENCE_READONLY_USERNAME}

export GOVERNANCE_AUTHENTICATOR_USERNAME=${DB_REF_GOVERNANCE_AUTHENTICATOR_USERNAME}
export GOVERNANCE_ANON_USERNAME=${DB_REF_GOVERNANCE_ANON_USERNAME}
export GOVERNANCE_SERVICE_USERNAME=${DB_REF_GOVERNANCE_SERVICE_USERNAME}
export GOVERNANCE_READONLY_USERNAME=${DB_REF_GOVERNANCE_READONLY_USERNAME}

export REFDB_URL="postgresql://${GOVERNANCE_OWNERNAME}:${GOVERNANCE_OWNERPASSWORD}@${DB_REF_HOSTNAME}:${DB_REF_PORT}/${DB_REF_DEFAULT_DBNAME}${DB_REF_OPTIONS}"

# Clear reference DB
psql ${REFDB_URL} -c "drop database if exists ${DB_REF_REFERENCE_DBNAME};"

# Clear roles and schemas
psql ${ROOT_URL} -c "drop table if exists flyway_schema_history; drop role if exists ${GOVERNANCE_AUTHENTICATOR_USERNAME}; drop role if exists ${REFERENCE_AUTHENTICATOR_USERNAME}; drop role if exists ${GOVERNANCE_ANON_USERNAME}; drop role if exists ${GOVERNANCE_SERVICE_USERNAME}; drop role if exists ${GOVERNANCE_READONLY_USERNAME}; drop role if exists ${GOVERNANCE_OWNERNAME}; drop role if exists ${REFERENCE_OWNERNAME}; drop role if exists ${REFERENCE_ANONUSERNAME}; drop role if exists ${REFERENCE_SERVICEUSERNAME}; drop role if exists ${REFERENCE_READONLYUSERNAME};"
